cutscene Finish
all done but get
SerializedObjectNotCreatableException: Object at index 0 is null
UnityEditor.Editor.CreateSerializedObject () (at <24e1ed8728684ea3ae446f80787d18de>:0)
UnityEditor.Editor.GetSerializedObjectInternal () (at <24e1ed8728684ea3ae446f80787d18de>:0)
UnityEditor.Editor.get_serializedObject () (at <24e1ed8728684ea3ae446f80787d18de>:0)
UnityEditor.Timeline.Signals.SignalReceiverInspector.OnEnable () (at ./Library/PackageCache/com.unity.timeline@1.7.6/Editor/Signals/SignalReceiverInspector.cs:26)